"""Build the README results sections from the saved results files.

Nothing here invents a number. Every value is read back from ``results/metrics``,
so the README cannot drift away from what the code actually produced. The rendered
block is injected into ``README.md`` between the AUTOGENERATED markers.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd

from . import config

BEGIN_MARKER = "<!-- BEGIN:AUTOGENERATED-RESULTS -->"
END_MARKER = "<!-- END:AUTOGENERATED-RESULTS -->"
HEADLINE_BEGIN = "<!-- BEGIN:AUTOGENERATED-HEADLINE -->"
HEADLINE_END = "<!-- END:AUTOGENERATED-HEADLINE -->"


def _read_json(name: str) -> dict[str, Any]:
    """Read a metrics JSON file by stem."""
    path = config.METRICS_DIR / f"{name}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv(name: str) -> pd.DataFrame:
    """Read a metrics CSV file by stem."""
    return pd.read_csv(config.METRICS_DIR / f"{name}.csv")


def _fmt(value: float | None, digits: int = 3) -> str:
    """Format a float for a markdown table, or an em dash when absent."""
    if value is None or pd.isna(value):
        return "—"
    return f"{value:.{digits}f}"


def _ci(cis: dict[str, dict[str, float]], metric: str) -> str:
    """Render a bootstrap confidence interval as ``[lo, hi]``."""
    if metric not in cis:
        return "—"
    return f"[{cis[metric]['lower']:.3f}, {cis[metric]['upper']:.3f}]"


def build_model_table() -> str:
    """Render the model/baseline leaderboard as a markdown table."""
    leaderboard = _read_csv("model_leaderboard")
    final = _read_json("final_evaluation")
    best = final["best_model"]

    lines = [
        "| Model | Type | CV ROC-AUC (5×3, train) | Imputer chosen by CV |",
        "|---|---|---|---|",
    ]
    for _, row in leaderboard.iterrows():
        marker = " **(final)**" if row["model"] == best else ""
        imputer = row.get("chosen_imputer")
        indicator = row.get("chosen_imputer_add_indicator")
        if pd.isna(imputer) if not isinstance(imputer, str) else False:
            imputer_text = "—"
        elif isinstance(imputer, str):
            imputer_text = imputer + (" + indicators" if indicator is True else "")
        else:
            imputer_text = "—"
        lines.append(
            f"| {row['model']}{marker} | {row['kind']} | "
            f"{_fmt(row['cv_roc_auc_mean'])} ± {_fmt(row['cv_roc_auc_std'])} | {imputer_text} |"
        )
    return "\n".join(lines)


def build_headline_table() -> str:
    """Render the final test-set comparison against both baselines."""
    final = _read_json("final_evaluation")
    model = final["final_model_test_at_chosen_threshold"]
    cis = final["final_model_test_bootstrap_ci_95"]
    rule = final["rule_baseline_test"]
    dummy = final["dummy_baseline_test"]
    best = final["best_model"]
    threshold = final["threshold_choice"]["threshold"]

    header = (
        "| Metric (UNSAFE = positive) | "
        f"**{best} @ thr {threshold:.3f}** | 95% CI (bootstrap) | "
        "Guideline rule baseline | Dummy (majority class) |"
    )
    lines = [header, "|---|---|---|---|---|"]
    rows = [
        ("ROC-AUC", "roc_auc", True),
        ("PR-AUC (average precision)", "pr_auc", True),
        ("Recall on UNSAFE", "recall_unsafe", True),
        ("Precision on UNSAFE", "precision_unsafe", True),
        ("F1 on UNSAFE", "f1_unsafe", True),
        ("Balanced accuracy", "balanced_accuracy", True),
        ("Share of samples flagged for lab testing", "flag_rate", False),
    ]
    for label, key, has_ci in rows:
        lines.append(
            f"| {label} | {_fmt(model.get(key))} | "
            f"{_ci(cis, key) if has_ci else '—'} | "
            f"{_fmt(rule.get(key))} | {_fmt(dummy.get(key))} |"
        )
    lines.append(
        f"| Unsafe samples missed (false negatives) | {model['false_negatives']} | — | "
        f"{rule['false_negatives']} | {dummy['false_negatives']} |"
    )
    lines.append(
        f"| Test samples | {model['n_samples']} | — | "
        f"{rule['n_samples']} | {dummy['n_samples']} |"
    )
    return "\n".join(lines)


def build_threshold_section() -> str:
    """Describe the chosen operating threshold and the cost of the trade-off."""
    final = _read_json("final_evaluation")
    choice = final["threshold_choice"]
    chosen = final["final_model_test_at_chosen_threshold"]
    default = final["final_model_test_at_default_threshold"]

    met = "reached" if choice["target_met"] else "**NOT reachable**"
    extra_flags = chosen["flag_rate"] - default["flag_rate"]
    extra_recall = chosen["recall_unsafe"] - default["recall_unsafe"]

    return "\n".join(
        [
            f"The operating threshold was chosen on **cross-validated predictions over the "
            f"training set only** (the test set was untouched at this point). Among all "
            f"thresholds reaching at least **{choice['target_recall']:.0%} recall on the "
            f"UNSAFE class**, we keep the one with the highest precision.",
            "",
            f"- Recall target of {choice['target_recall']:.0%} was {met} in cross-validation.",
            f"- **Chosen threshold: {choice['threshold']:.4f}** on predicted P(UNSAFE) "
            f"(cross-validated recall {choice['achieved_recall']:.3f}, "
            f"precision {choice['achieved_precision']:.3f}).",
            "",
            "**What the trade-off costs, measured on the test set:**",
            "",
            "| | Default threshold 0.5 | Chosen threshold " f"{choice['threshold']:.3f} | Change |",
            "|---|---|---|---|",
            f"| Recall on UNSAFE | {_fmt(default['recall_unsafe'])} | "
            f"{_fmt(chosen['recall_unsafe'])} | {extra_recall:+.3f} |",
            f"| Precision on UNSAFE | {_fmt(default['precision_unsafe'])} | "
            f"{_fmt(chosen['precision_unsafe'])} | "
            f"{chosen['precision_unsafe'] - default['precision_unsafe']:+.3f} |",
            f"| Unsafe samples missed | {default['false_negatives']} | "
            f"{chosen['false_negatives']} | "
            f"{chosen['false_negatives'] - default['false_negatives']:+d} |",
            f"| Safe samples sent for testing anyway | {default['false_positives']} | "
            f"{chosen['false_positives']} | "
            f"{chosen['false_positives'] - default['false_positives']:+d} |",
            f"| Share of all samples flagged | {_fmt(default['flag_rate'])} | "
            f"{_fmt(chosen['flag_rate'])} | {extra_flags:+.3f} |",
            "",
            f"In plain terms: moving from the default cut-off to the risk-aware one "
            f"catches **{chosen['true_positives'] - default['true_positives']} more unsafe "
            f"samples** out of {chosen['true_positives'] + chosen['false_negatives']} in the "
            f"test set, at the cost of sending "
            f"**{chosen['false_positives'] - default['false_positives']} more safe samples** "
            f"to the lab.",
        ]
    )


def build_rule_table() -> str:
    """Render the verified guideline limits actually used by the rule baseline."""
    rule = _read_json("rule_baseline")
    lines = [
        "| Parameter | Limit applied | Source | Rows breaching |",
        "|---|---|---|---|",
    ]
    for name, info in rule["parameters_used"].items():
        if info["lower"] is not None and info["upper"] is not None:
            limit = f"{info['lower']}–{info['upper']} {info['unit']}"
        elif info["upper"] is not None:
            limit = f"≤ {info['upper']} {info['unit']}"
        else:
            limit = f"≥ {info['lower']} {info['unit']}"
        lines.append(
            f"| `{name}` | {limit} | {info['source']} | "
            f"{info['n_violations']:,} ({info['pct_violations']:.1f}%) |"
        )
    lines.append("")
    lines.append("**Excluded from the rule — no numeric limit could be verified:**")
    lines.append("")
    for name, reason in rule["parameters_excluded"].items():
        lines.append(f"- `{name}` — {reason}")
    return "\n".join(lines)


def build_imputer_table() -> str:
    """Render the cross-validated imputation strategy comparison."""
    frame = _read_csv("imputer_comparison")
    lines = ["| Imputation strategy | CV ROC-AUC (train) |", "|---|---|"]
    for _, row in frame.iterrows():
        lines.append(
            f"| `{row['imputer']}` | {_fmt(row['cv_roc_auc_mean'])} ± "
            f"{_fmt(row['cv_roc_auc_std'])} |"
        )
    return "\n".join(lines)


def build_importance_table() -> str:
    """Render permutation importance for the final model."""
    frame = _read_csv("permutation_importance")
    lines = [
        "| Feature | Drop in test ROC-AUC when shuffled | In the guideline rule? |",
        "|---|---|---|",
    ]
    for _, row in frame.iterrows():
        in_rule = "yes" if row["feature"] in config.PARAMETER_LIMITS else "no (unverified limit)"
        lines.append(
            f"| `{row['feature']}` | {row['importance_mean']:.4f} ± "
            f"{row['importance_std']:.4f} | {in_rule} |"
        )
    return "\n".join(lines)


def build_dataset_table() -> str:
    """Render the dataset audit summary."""
    audit = _read_json("data_audit")
    missing = audit["missingness"]
    lines = [
        "| Feature | Unit | Missing | % missing |",
        "|---|---|---|---|",
    ]
    for name in config.FEATURES:
        info = missing.get(name, {"n_missing": 0, "pct_missing": 0.0})
        lines.append(
            f"| `{name}` | {config.FEATURE_UNITS[name]} | {int(info['n_missing']):,} | "
            f"{info['pct_missing']:.1f}% |"
        )
    lines.append(
        f"| `{config.RAW_TARGET}` (target) "
        "| 1 = potable (SAFE), 0 = not potable (UNSAFE) | 0 | 0.0% |"
    )
    return "\n".join(lines)


def build_error_profile_table() -> str:
    """Compare median feature values for missed vs. caught unsafe samples."""
    frame = _read_csv("error_analysis_missed_vs_caught")
    frame = frame.assign(
        relative_gap=lambda d: (d["median_gap"] / d["median_caught_unsafe"]).abs()
    ).sort_values("relative_gap", ascending=False)
    lines = [
        "| Parameter | Median (missed unsafe) | Median (caught unsafe) | Relative difference |",
        "|---|---|---|---|",
    ]
    for _, row in frame.iterrows():
        lines.append(
            f"| `{row['feature']}` | {row['median_missed_unsafe']:.3g} | "
            f"{row['median_caught_unsafe']:.3g} | {row['relative_gap']:.1%} |"
        )
    return "\n".join(lines)


def _largest_error_gap() -> str:
    """Describe the single largest relative median gap between missed and caught."""
    frame = _read_csv("error_analysis_missed_vs_caught")
    frame = frame.assign(
        relative_gap=lambda d: (d["median_gap"] / d["median_caught_unsafe"]).abs()
    ).sort_values("relative_gap", ascending=False)
    top = frame.iloc[0]
    return f"`{top['feature']}` at {top['relative_gap']:.1%}"


def build_results_block() -> str:
    """Assemble the complete autogenerated results block."""
    audit = _read_json("data_audit")
    final = _read_json("final_evaluation")
    meta = _read_json("run_metadata")
    errors = _read_json("error_analysis")
    model = final["final_model_test_at_chosen_threshold"]
    cis = final["final_model_test_bootstrap_ci_95"]

    parts = [
        BEGIN_MARKER,
        "<!-- Generated by scripts/run_all.py via src/aqua_seq/report.py. "
        "Do not edit by hand. -->",
        "",
        "### Headline result",
        "",
        f"The best model was **{final['best_model']}**, selected by cross-validated ROC-AUC on "
        f"the training set. On the held-out test set ({final['n_test']:,} samples, "
        f"{final['test_unsafe_prevalence']:.1%} unsafe) it reached "
        f"**ROC-AUC {model['roc_auc']:.3f}** {_ci(cis, 'roc_auc')} and "
        f"**PR-AUC {model['pr_auc']:.3f}** {_ci(cis, 'pr_auc')}.",
        "",
        f"At the risk-aware threshold of "
        f"**{final['threshold_choice']['threshold']:.3f}** it catches "
        f"**{model['recall_unsafe']:.1%} of unsafe samples** at "
        f"**{model['precision_unsafe']:.1%} precision**, flagging "
        f"**{model['flag_rate']:.1%}** of all samples for lab testing and still missing "
        f"**{model['false_negatives']} unsafe samples** out of "
        f"{model['true_positives'] + model['false_negatives']}.",
        "",
        "### All models and baselines",
        "",
        build_model_table(),
        "",
        "*Cross-validated on the training set only, 5-fold × 3 repeats. "
        "Hyperparameters were searched with "
        f"{config.N_SEARCH_ITER}-candidate randomised search over 5-fold CV; the imputation "
        "strategy was part of that search.*",
        "",
        "### Final model vs. baselines on the held-out test set",
        "",
        build_headline_table(),
        "",
        "*The test set was used exactly once, for this table. Confidence intervals are "
        f"{config.N_BOOTSTRAP:,}-resample bootstrap percentile intervals.*",
        "",
        "### The chosen decision threshold",
        "",
        build_threshold_section(),
        "",
        "### Guideline-based rule baseline",
        "",
        build_rule_table(),
        "",
        "### Imputation strategies compared under cross-validation",
        "",
        build_imputer_table(),
        "",
        "### What the model actually uses",
        "",
        build_importance_table(),
        "",
        "### Dataset audit",
        "",
        f"- **{audit['n_rows']:,} rows**, {audit['n_features']} features, "
        f"{audit['n_duplicate_rows']} duplicate rows.",
        f"- Class balance: **{audit['class_counts'][config.POSITIVE_CLASS_NAME]:,} UNSAFE "
        f"({audit['unsafe_prevalence']:.1%})** vs "
        f"{audit['class_counts'][config.NEGATIVE_CLASS_NAME]:,} SAFE. "
        "Note that UNSAFE is the *majority* class here.",
        f"- {audit['impossible_values']['ph_outside_0_14']} pH values outside the physically "
        f"possible 0–14 range; {audit['impossible_values']['negative_values_any_feature']} "
        "negative measurements.",
        "",
        build_dataset_table(),
        "",
        "### Error analysis",
        "",
        "| Outcome | Count |",
        "|---|---|",
        *[f"| {k} | {v:,} |" for k, v in errors["outcome_counts"].items()],
        "",
        f"Median predicted P(UNSAFE) was {_fmt(errors['caught_unsafe_score_median'])} for unsafe "
        f"samples the model caught and {_fmt(errors['missed_unsafe_score_median'])} for unsafe "
        "samples it missed. Those scores differ by construction — the threshold is what "
        "separates them — so the informative comparison is the underlying measurements:",
        "",
        build_error_profile_table(),
        "",
        "Across all nine parameters the missed and caught unsafe samples look nearly "
        f"identical; the largest relative difference in medians is "
        f"{_largest_error_gap()}. There is no region of feature space where the missed "
        "samples live, which is why this is a weak feature–label relationship rather than a "
        "fixable tuning problem.",
        "",
        "### Run metadata",
        "",
        f"- Python {meta['python_version']}, numpy {meta['numpy_version']}, "
        f"pandas {meta['pandas_version']}",
        f"- Random seed: `{meta['random_seed']}`",
        f"- Full pipeline runtime: **{meta['runtime_seconds'] / 60:.1f} minutes**",
        "",
        END_MARKER,
    ]
    return "\n".join(parts)


def build_headline_block() -> str:
    """Assemble the short answer-first block that opens the README."""
    final = _read_json("final_evaluation")
    model = final["final_model_test_at_chosen_threshold"]
    dummy = final["dummy_baseline_test"]
    rule = final["rule_baseline_test"]
    cis = final["final_model_test_bootstrap_ci_95"]
    total_unsafe = model["true_positives"] + model["false_negatives"]
    tests_saved = dummy["flag_rate"] - model["flag_rate"]

    return "\n".join(
        [
            HEADLINE_BEGIN,
            "",
            "## Summary",
            "",
            f"{final['best_model']} reaches "
            f"**ROC-AUC {model['roc_auc']:.3f}** ({_ci(cis, 'roc_auc')}) on a test set used "
            f"once. At the risk-aware threshold it catches "
            f"**{model['recall_unsafe']:.0%} of unsafe samples** at "
            f"**{model['precision_unsafe']:.0%} precision**, saving ~"
            f"**{tests_saved:.0%} of lab capacity** versus testing everything — and missing "
            f"**{model['false_negatives']} of {total_unsafe}** unsafe samples.",
            "",
            "| | Catches unsafe | Precision | Sends to lab |",
            "|---|---|---|---|",
            f"| **{final['best_model']}** (final) | {model['recall_unsafe']:.0%} | "
            f"{model['precision_unsafe']:.0%} | {model['flag_rate']:.0%} |",
            f"| Guideline rule (WHO/BIS/EPA) | {rule['recall_unsafe']:.0%} | "
            f"{rule['precision_unsafe']:.0%} | {rule['flag_rate']:.0%} |",
            f"| Test everything (dummy) | {dummy['recall_unsafe']:.0%} | "
            f"{dummy['precision_unsafe']:.0%} | {dummy['flag_rate']:.0%} |",
            "",
            HEADLINE_END,
        ]
    )


def build_compact_block() -> str:
    """Assemble the condensed results block used in the README.

    The exhaustive version is written to ``results/metrics/readme_sections.md`` so the
    README can stay short without the detail being lost.
    """
    final = _read_json("final_evaluation")
    audit = _read_json("data_audit")
    meta = _read_json("run_metadata")
    model = final["final_model_test_at_chosen_threshold"]
    cis = final["final_model_test_bootstrap_ci_95"]
    choice = final["threshold_choice"]
    leaderboard = _read_csv("model_leaderboard")

    # Test metrics exist only for the final model and the two baselines: every other
    # candidate was selected on cross-validation alone and never scored on the test set.
    tested = {
        final["best_model"]: model,
        "Guideline rule baseline": final["rule_baseline_test"],
        "Dummy (majority class)": final["dummy_baseline_test"],
    }

    rows = []
    for _, row in leaderboard.iterrows():
        name = row["model"]
        label = f"{name}{' **(final)**' if name == final['best_model'] else ''}"
        test = tested.get(name)
        if test is None:
            cells = "— | — | —"
        else:
            cells = (
                f"{_fmt(test['roc_auc'])} | {_fmt(test['recall_unsafe'])} | "
                f"{_fmt(test['precision_unsafe'])}"
            )
        rows.append(
            f"| {label} | {_fmt(row['cv_roc_auc_mean'])} ± "
            f"{_fmt(row['cv_roc_auc_std'])} | {cells} |"
        )

    return "\n".join(
        [
            BEGIN_MARKER,
            "",
            f"{audit['n_rows']:,} samples, {audit['unsafe_prevalence']:.1%} unsafe. "
            f"Cross-validated on the training set (5-fold × 3); test set "
            f"({final['n_test']:,} samples) scored once at threshold "
            f"{choice['threshold']:.3f}.",
            "",
            "| Model | CV ROC-AUC | Test ROC-AUC | Recall | Precision |",
            "|---|---|---|---|---|",
            *rows,
            "",
            f"95% CI ({config.N_BOOTSTRAP:,}-resample bootstrap) for the final model: "
            f"ROC-AUC {_ci(cis, 'roc_auc')}, PR-AUC {_fmt(model['pr_auc'])} "
            f"{_ci(cis, 'pr_auc')}, recall {_ci(cis, 'recall_unsafe')}, "
            f"precision {_ci(cis, 'precision_unsafe')}.",
            "",
            f"*Full tables in "
            f"[`results/metrics/readme_sections.md`](results/metrics/readme_sections.md) — "
            f"hyperparameters, guideline limits, imputer comparison, feature importance, "
            f"error profiles. Runtime {meta['runtime_seconds'] / 60:.0f} min, seed "
            f"`{meta['random_seed']}`.*",
            "",
            END_MARKER,
        ]
    )


def _inject(text: str, begin: str, end: str, block: str) -> str:
    """Replace the content between two markers, leaving the rest of the text intact."""
    if begin in text and end in text:
        return text.split(begin)[0] + block + text.split(end)[1]
    return text


def build_readme_sections(readme_path: Path | None = None) -> Path:
    """Write the results block and inject it into the README between markers.

    Both the opening headline block and the full results block are regenerated, so no
    number anywhere in the README can drift away from the saved results files.

    Args:
        readme_path: Override for the README location.

    Returns:
        Path of the standalone results markdown file.
    """
    block = build_results_block()
    standalone = config.METRICS_DIR / "readme_sections.md"
    standalone.write_text(block, encoding="utf-8")

    readme = readme_path or (config.PROJECT_ROOT / "README.md")
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        text = _inject(text, HEADLINE_BEGIN, HEADLINE_END, build_headline_block())
        text = _inject(text, BEGIN_MARKER, END_MARKER, build_compact_block())
        readme.write_text(text, encoding="utf-8")
    return standalone
